# ----------------------------------------------
# Script Generated by PCB Stack-up & Via Visualizer
# ----------------------------------------------
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.GetActiveProject()
if oProject is None:
    raise Exception("Loading project failed: no active AEDT project.")
oDesign = oProject.GetActiveDesign()
if oDesign is None:
    raise Exception("Loading HFSS design failed: no active AEDT design.")
oEditor = oDesign.SetActiveEditor("3D Modeler")

# Global stack-up variables
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:PCB_variables",
                    "PropType:="        , "SeparatorProp",
                    "UserDef:="         , True,
                    "Value:="           , ""
                ],
                [
                    "NAME:DielX",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "10mm"
                ],
                [
                    "NAME:DielY",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "10mm"
                ]
            ]
        ]
    ])

# Z = 0 at the base of the lowest dielectric
# [L5] New Layer
# External bottom metal: referenced to the lower face of the first dielectric.
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:L5_h",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "35um"
                ],
                [
                    "NAME:L5_high",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "d33_low"
                ],
                [
                    "NAME:L5_low",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "L5_high-L5_h"
                ]
            ]
        ]
    ])

# [d33] New Layer
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:d33_low",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "0mm"
                ],
                [
                    "NAME:d33_h",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "0.1mm"
                ],
                [
                    "NAME:d33_high",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "d33_low+d33_h"
                ]
            ]
        ]
    ])
oEditor.CreateBox(
    [
        "NAME:BoxParameters",
        "XPosition:="        , "-DielX/2",
        "YPosition:="        , "-DielY/2",
        "ZPosition:="        , "d33_low",
        "XSize:="            , "DielX",
        "YSize:="            , "DielY",
        "ZSize:="            , "d33_h"
    ], 
    [
        "NAME:Attributes",
        "Name:="             , "d33_box",
        "Flags:="            , "",
        "Color:="            , "(112 128 144)",
        "Transparency:="     , 0.35,
        "PartCoordinateSystem:=", "Global",
        "UDMId:="            , "",
        "MaterialValue:="     , "\"FR4_epoxy\"",
        "SurfaceMaterialValue:=", "\"\"",
        "SolveInside:="      , True,
        "ShellElement:="     , False,
        "ShellElementThickness:=", "0mm",
        "ReferenceTemperature:=", "20cel",
        "IsMaterialEditable:=", True,
        "UseMaterialAppearance:=", False,
        "IsLightweight:="    , False
    ])

# [L2] Bottom Copper
# core-metal-core: the copper sits on the upper face of the lower core.
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:L2_low",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "d33_high"
                ],
                [
                    "NAME:L2_h",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "35um"
                ],
                [
                    "NAME:L2_high",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "L2_low+L2_h"
                ]
            ]
        ]
    ])

# [D1] FR4 Core
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:D1_low",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "d33_high"
                ],
                [
                    "NAME:D1_h",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "1.5mm"
                ],
                [
                    "NAME:D1_high",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "D1_low+D1_h"
                ]
            ]
        ]
    ])
oEditor.CreateBox(
    [
        "NAME:BoxParameters",
        "XPosition:="        , "-DielX/2",
        "YPosition:="        , "-DielY/2",
        "ZPosition:="        , "D1_low",
        "XSize:="            , "DielX",
        "YSize:="            , "DielY",
        "ZSize:="            , "D1_h"
    ], 
    [
        "NAME:Attributes",
        "Name:="             , "D1_box",
        "Flags:="            , "",
        "Color:="            , "(112 128 144)",
        "Transparency:="     , 0.35,
        "PartCoordinateSystem:=", "Global",
        "UDMId:="            , "",
        "MaterialValue:="     , "\"FR4_epoxy\"",
        "SurfaceMaterialValue:=", "\"\"",
        "SolveInside:="      , True,
        "ShellElement:="     , False,
        "ShellElementThickness:=", "0mm",
        "ReferenceTemperature:=", "20cel",
        "IsMaterialEditable:=", True,
        "UseMaterialAppearance:=", False,
        "IsLightweight:="    , False
    ])

# [L1] Top Copper
# External top metal: sits on the upper face of the dielectric below.
oDesign.ChangeProperty(
    [
        "NAME:AllTabs",
        [
            "NAME:LocalVariableTab",
            [
                "NAME:PropServers", 
                "LocalVariables"
            ],
            [
                "NAME:NewProps",
                [
                    "NAME:L1_low",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "D1_high"
                ],
                [
                    "NAME:L1_h",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "35um"
                ],
                [
                    "NAME:L1_high",
                    "PropType:="        , "VariableProp",
                    "UserDef:="         , True,
                    "Value:="           , "L1_low+L1_h"
                ]
            ]
        ]
    ])
