"""
HFSS Script Exporter for PCB Stack-up.

Generates a Python script compatible with Ansys Electronics Desktop (AEDT) that:
1. Declares global variables for dielectric dimensions (DielX, DielY)
2. Creates variables for dielectric layers (Dx_low, Dx_h, Dx_high)
3. Creates variables for metal layers (Lx_low, Lx_h, Lx_high) with proper
   core/prepreg interaction logic
4. Generates Box objects for dielectric layers only
"""


def _format_thickness(thickness_mm):
    """Format thickness value, converting to mm or um as appropriate."""
    val = float(thickness_mm)
    if val < 0.05:  # Less than 50um, use um for readability
        return f"{val * 1000:.2f}um"
    else:
        return f"{val:.4f}mm"


def _get_layer_by_id(layers, layer_id):
    """Get layer dict by ID."""
    for layer in layers:
        if layer['id'] == layer_id:
            return layer
    return None


def _is_dielectric(layer):
    """Check if layer is a dielectric (core or prepreg)."""
    return layer['type'] == 'dielectric'


def _get_dielectric_category(layer):
    """Return 'core' or 'prepreg' for dielectric layers."""
    mat_ref = layer.get('material_ref', '').lower()
    name = layer.get('name', '').lower()
    if 'prepreg' in mat_ref or 'prepreg' in name:
        return 'prepreg'
    elif 'core' in mat_ref or 'core' in name:
        return 'core'
    # Default: if it's dielectric but not explicitly prepreg, assume core
    return 'core'


def generate_hfss_script(stackup_data):
    """
    Generate HFSS AEDT-compatible Python script from stackup_data.

    Logic:
    - Layers are processed from BOTTOM to TOP (reversing the top-down list)
    - Z=0 is at the base of the lowest dielectric
    - Dielectrics get Box objects with variables: {ID}_low, {ID}_h, {ID}_high
    - Metals get only variables (no boxes): {ID}_low, {ID}_h, {ID}_high
    - Metal placement depends on adjacent dielectric types:
      * Case A (core-metal-core or external metal): metal sits ON TOP of lower dielectric
      * Case B (core-metal-prepreg or prepreg-metal-core): metal penetrates into prepreg
    """
    layers = stackup_data.get('layers', [])
    if not layers:
        return "# No layers defined in stackup_data."

    # Reverse layers: bottom-to-top processing
    layers_bottom_up = list(reversed(layers))

    script_lines = []

    # --- Header ---
    script_lines.append('# ----------------------------------------------')
    script_lines.append('# Script Generated by PCB Stack-up & Via Visualizer')
    script_lines.append(f'# Total Layers: {len(layers)}')
    script_lines.append('# ----------------------------------------------')
    script_lines.append('import ScriptEnv')
    script_lines.append('ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")')
    script_lines.append('oDesktop.RestoreWindow()')
    script_lines.append('oProject = oDesktop.SetActiveProject("Project1")')
    script_lines.append('oDesign = oProject.SetActiveDesign("HFSSDesign1")')
    script_lines.append('oEditor = oDesign.SetActiveEditor("3D Modeler")')
    script_lines.append('')

    # --- Global dielectric dimensions ---
    script_lines.append('# Global dielectric plan dimensions')
    for var_name, value in [('DielX', '10mm'), ('DielY', '10mm')]:
        script_lines.append(
            'oDesign.ChangeProperty(\n'
            '    [\n'
            '        "NAME:AllTabs",\n'
            '        [\n'
            '            "NAME:LocalVariableTab",\n'
            '            [\n'
            '                "NAME:PropServers",\n'
            '                "LocalVariables"\n'
            '            ],\n'
            '            [\n'
            '                "NAME:NewProps",\n'
            '                [\n'
            '                    "NAME:{}",\n'
            '                    "PropType:="		, "VariableProp",\n'
            '                    "UserDef:="		, True,\n'
            '                    "Value:="		, "{}"\n'
            '                ]\n'
            '            ]\n'
            '        ]\n'
            '    ])\n'.format(var_name, value)
        )
    script_lines.append('')

    # --- Build layer map for adjacency queries ---
    # Store info as we process: {layer_id: {low, h, high, type, category}}
    layer_info = {}
    box_counter = 0  # Track box creation order

    # First pass: identify all dielectric layers and their order from bottom
    dielectric_layers_bottom_up = []
    for layer in layers_bottom_up:
        if _is_dielectric(layer):
            dielectric_layers_bottom_up.append(layer)

    # Track cumulative Z height from dielectrics only
    current_z = 0.0

    # --- Create dielectric boxes and variables (bottom to top) ---
    script_lines.append('# ==========================================')
    script_lines.append('# DIELECTRIC LAYERS: Variables and Box Objects')
    script_lines.append('# ==========================================')

    for d_layer in dielectric_layers_bottom_up:
        d_id = d_layer['id']
        d_thick = float(d_layer['thickness'])
        d_category = _get_dielectric_category(d_layer)
        d_color_hex = d_layer.get('color_hex', '#8FAF8F')

        # Convert hex color to RGB tuple for HFSS
        r, g, b = _hex_to_rgb(d_color_hex)
        color_str = f"({r} {g} {b})"

        box_counter += 1
        box_name = f"Box{box_counter}"

        # Variables for this dielectric
        d_low = current_z
        d_h = d_thick
        d_high = current_z + d_thick

        layer_info[d_id] = {
            'low': d_low,
            'h': d_h,
            'high': d_high,
            'type': 'dielectric',
            'category': d_category
        }

        # Generate _low variable
        low_val_str = _format_thickness(d_low)
        script_lines.append(f'# {d_id} bottom coordinate')
        script_lines.append(
            _gen_change_property_local_var(d_id + '_low', low_val_str)
        )

        # Update box Z position to use variable
        if box_counter == 1:
            # First box: need to create it first with placeholder, then modify
            script_lines.append(f'# Create {d_id} Box')
            script_lines.append(
                _gen_create_box(box_name, d_id + '_low', d_id + '_h', color_str)
            )
        else:
            # Subsequent boxes: create with variables
            script_lines.append(f'# Create {d_id} Box')
            script_lines.append(
                _gen_create_box(box_name, d_id + '_low', d_id + '_h', color_str)
            )

        # Generate _high variable
        high_val_str = f"{d_id}_low+{d_id}_h"
        script_lines.append(f'# {d_id} top coordinate')
        script_lines.append(
            _gen_change_property_local_var(d_id + '_high', high_val_str)
        )

        # Update ZSize to use _high variable
        script_lines.append(
            _gen_change_geometry_prop(box_name, 'ZSize', d_id + '_high')
        )

        # Update box Z position to use _low variable
        script_lines.append(
            _gen_change_geometry_prop(box_name, 'Position', None,
                                       z_val=d_id + '_low')
        )

        # Update current_z for next dielectric
        current_z = d_high

    script_lines.append('')

    # --- Second pass: generate metal layer variables (bottom to top) ---
    script_lines.append('# ==========================================')
    script_lines.append('# METAL LAYERS: Variables (no Box objects)')
    script_lines.append('# ==========================================')

    metal_layers_bottom_up = [l for l in layers_bottom_up if not _is_dielectric(l)]

    for m_layer in metal_layers_bottom_up:
        m_id = m_layer['id']
        m_thick = float(m_layer['thickness'])

        # Determine placement logic based on adjacent dielectrics
        m_idx_bottom_up = layers_bottom_up.index(m_layer)

        # Find adjacent dielectrics (below and above this metal)
        lower_dielectric = None
        upper_dielectric = None

        # Search downward in bottom-up list for lower dielectric
        for i in range(m_idx_bottom_up - 1, -1, -1):
            if _is_dielectric(layers_bottom_up[i]):
                lower_dielectric = layers_bottom_up[i]
                break

        # Search upward in bottom-up list for upper dielectric
        for i in range(m_idx_bottom_up + 1, len(layers_bottom_up)):
            if _is_dielectric(layers_bottom_up[i]):
                upper_dielectric = layers_bottom_up[i]
                break

        # Determine metal Z placement
        if lower_dielectric is None and upper_dielectric is not None:
            # External metal at bottom: sits below upper dielectric
            # L_high = upper_D_low, L_low = L_high - L_h
            upper_d_id = upper_dielectric['id']
            m_high_expr = f"{upper_d_id}_low"
            m_low_expr = f"{m_high_expr}-{m_id}_h"
            m_low_val = float(layer_info[upper_d_id]['low']) - m_thick
            m_high_val = layer_info[upper_d_id]['low']

        elif lower_dielectric is not None and upper_dielectric is None:
            # External metal at top: sits on lower dielectric
            # L_low = lower_D_high, L_high = L_low + L_h
            lower_d_id = lower_dielectric['id']
            m_low_expr = f"{lower_d_id}_high"
            m_high_expr = f"{m_low_expr}+{m_id}_h"
            m_low_val = layer_info[lower_d_id]['high']
            m_high_val = m_low_val + m_thick

        elif lower_dielectric is not None and upper_dielectric is not None:
            lower_d_id = lower_dielectric['id']
            upper_d_id = upper_dielectric['id']
            lower_cat = layer_info[lower_d_id].get('category', 'core')
            upper_cat = layer_info[upper_d_id].get('category', 'core')

            if lower_cat == 'core' and upper_cat == 'core':
                # Case A: core-metal-core -> metal on top of lower dielectric
                m_low_expr = f"{lower_d_id}_high"
                m_high_expr = f"{m_low_expr}+{m_id}_h"
                m_low_val = layer_info[lower_d_id]['high']
                m_high_val = m_low_val + m_thick

            elif lower_cat == 'core' and upper_cat == 'prepreg':
                # Case B: core-metal-prepreg -> metal grows UP into prepreg
                # L_low = core_high, L_high = L_low + L_h
                m_low_expr = f"{lower_d_id}_high"
                m_high_expr = f"{m_low_expr}+{m_id}_h"
                m_low_val = layer_info[lower_d_id]['high']
                m_high_val = m_low_val + m_thick

            elif lower_cat == 'prepreg' and upper_cat == 'core':
                # Case B: prepreg-metal-core -> metal grows DOWN into prepreg
                # L_high = core_low, L_low = L_high - L_h
                m_high_expr = f"{upper_d_id}_low"
                m_low_expr = f"{m_high_expr}-{m_id}_h"
                m_low_val = layer_info[upper_d_id]['low'] - m_thick
                m_high_val = layer_info[upper_d_id]['low']

            elif lower_cat == 'prepreg' and upper_cat == 'prepreg':
                # prepreg-metal-prepreg -> grows upward into upper prepreg
                m_low_expr = f"{lower_d_id}_high"
                m_high_expr = f"{m_low_expr}+{m_id}_h"
                m_low_val = layer_info[lower_d_id]['high']
                m_high_val = m_low_val + m_thick
            else:
                # Fallback: default to sitting on lower dielectric
                m_low_expr = f"{lower_d_id}_high"
                m_high_expr = f"{m_low_expr}+{m_id}_h"
                m_low_val = layer_info[lower_d_id]['high']
                m_high_val = m_low_val + m_thick
        else:
            # No dielectrics at all (shouldn't happen, but handle gracefully)
            m_low_val = 0.0
            m_high_val = m_thick
            m_low_expr = "0mm"
            m_high_expr = _format_thickness(m_thick)

        layer_info[m_id] = {
            'low': m_low_val,
            'h': m_thick,
            'high': m_high_val,
            'type': 'metal',
            'low_expr': m_low_expr,
            'high_expr': m_high_expr
        }

    # Now generate the StackUp separator with ALL metal variables together
    # This matches the ScriptDielPCB.py structure exactly
    if metal_layers_bottom_up or dielectric_layers_bottom_up:
        lines = []
        lines.append('oDesign.ChangeProperty(')
        lines.append('    [')
        lines.append('        "NAME:AllTabs",')
        lines.append('        [')
        lines.append('            "NAME:LocalVariableTab",')
        lines.append('            [')
        lines.append('                "NAME:PropServers",')
        lines.append('                "LocalVariables"')
        lines.append('            ],')
        lines.append('            [')
        lines.append('                "NAME:NewProps",')
        lines.append('                [')
        lines.append('                    "NAME:StackUp",')
        lines.append('                    "PropType:="        , "SeparatorProp",')
        lines.append('                    "UserDef:="         , True,')
        lines.append('                    "Value:="           , ""')
        lines.append('                ],')

        # Add all metal layer variables to NewProps
        all_metal_vars = []
        for m_layer in metal_layers_bottom_up:
            m_id = m_layer['id']
            m_info = layer_info[m_id]
            all_metal_vars.append((f'{m_id}_low', m_info['low_expr'], 'VariableProp'))
            all_metal_vars.append((f'{m_id}_h', _format_thickness(m_info['h']), 'VariableProp'))
            all_metal_vars.append((f'{m_id}_high', m_info['high_expr'], 'VariableProp'))

        # Add dielectric _h variables to NewProps
        for d_layer in dielectric_layers_bottom_up:
            d_id = d_layer['id']
            all_metal_vars.append((f'{d_id}_h', _format_thickness(layer_info[d_id]['h']), 'VariableProp'))

        # Add all variables with proper comma handling
        for i, (var_name, var_value, var_type) in enumerate(all_metal_vars):
            is_last = (i == len(all_metal_vars) - 1)
            lines.append('                [')
            lines.append(f'                    "NAME:{var_name}",')
            lines.append(f'                    "PropType:="        , "{var_type}",')
            lines.append('                    "UserDef:="         , True,')
            lines.append(f'                    "Value:="           , "{var_value}"')
            if is_last:
                lines.append('                ]')
            else:
                lines.append('                ],')

        lines.append('            ],')
        lines.append('            [')
        lines.append('                "NAME:ChangedProps",')
        lines.append('                [')
        lines.append('                    "NAME:StackUp",')
        lines.append('                    "NewRowPosition:=" , 0')
        lines.append('                ],')

        # Add D_high re-expression and D_h repositioning for each dielectric
        changed_props_items = []
        for d_layer in dielectric_layers_bottom_up:
            d_id = d_layer['id']
            changed_props_items.append((f'{d_id}_high', f'"Value:="           , "{d_id}_low+{d_id}_h"'))
            changed_props_items.append((f'{d_id}_h', f'"NewRowPosition:=" , 5'))

        for i, (var_name, prop_line) in enumerate(changed_props_items):
            is_last = (i == len(changed_props_items) - 1)
            lines.append('                [')
            lines.append(f'                    "NAME:{var_name}",')
            lines.append(f'                    {prop_line}')
            if is_last:
                lines.append('                ]')
            else:
                lines.append('                ],')

        lines.append('            ]')
        lines.append('        ]')
        lines.append('    ]')
        lines.append('])')
        
        # Debug: count brackets
        debug_opens = sum(l.count('[') for l in lines)
        debug_closes = sum(l.count(']') for l in lines)
        if debug_opens != debug_closes:
            print(f"WARNING: StackUp section has {debug_opens} [ but {debug_closes} ]")
        
        script_lines.extend(lines)
        script_lines.append('')

    return '\n'.join(script_lines)


def _hex_to_rgb(hex_color):
    """Convert hex color to RGB tuple (0-255)."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) != 6:
        return (143, 175, 143)  # Default green-ish
    try:
        r = int(hex_color[0:2], 16)
        g = int(hex_color[2:4], 16)
        b = int(hex_color[4:6], 16)
        return (r, g, b)
    except ValueError:
        return (143, 175, 143)


def _gen_change_property_local_var(var_name, value):
    """Generate ChangeProperty call for a local variable."""
    return (
        'oDesign.ChangeProperty(\n'
        '    [\n'
        '        "NAME:AllTabs",\n'
        '        [\n'
        '            "NAME:LocalVariableTab",\n'
        '            [\n'
        '                "NAME:PropServers",\n'
        '                "LocalVariables"\n'
        '            ],\n'
        '            [\n'
        '                "NAME:NewProps",\n'
        '                [\n'
        '                    "NAME:{}",\n'
        '                    "PropType:="		, "VariableProp",\n'
        '                    "UserDef:="		, True,\n'
        '                    "Value:="		, "{}"\n'
        '                ]\n'
        '            ]\n'
        '        ]\n'
        '    ])\n'.format(var_name, value)
    )


def _gen_create_box(box_name, z_position, z_size, color):
    """Generate CreateBox call with variable parameters."""
    return (
        'oEditor.CreateBox(\n'
        '	[\n'
        '		"NAME:BoxParameters",\n'
        '		"XPosition:="		, "-DielX/2",\n'
        '		"YPosition:="		, "-DielY/2",\n'
        '		"ZPosition:="		, "{}",\n'
        '		"XSize:="		, "DielX",\n'
        '		"YSize:="		, "DielY",\n'
        '		"ZSize:="		, "{}"\n'
        '	],\n'
        '	[\n'
        '		"NAME:Attributes",\n'
        '		"Name:="		, "{}",\n'
        '		"Flags:="		, "",\n'
        '		"Color:="		, "{}",\n'
        '		"Transparency:="	, 0,\n'
        '		"PartCoordinateSystem:=", "Global",\n'
        '		"UDMId:="		, "",\n'
        '		"MaterialValue:="	, "\\"vacuum\\"",\n'
        '		"SurfaceMaterialValue:=", "\\"",\n'
        '		"SolveInside:="		, True,\n'
        '		"ShellElement:="	, False,\n'
        '		"ShellElementThickness:=", "0mm",\n'
        '		"ReferenceTemperature:=", "20cel",\n'
        '		"IsMaterialEditable:="	, True,\n'
        '		"UseMaterialAppearance:=", False,\n'
        '		"IsLightweight:="	, False\n'
        '	])\n'.format(z_position, z_size, box_name, color)
    )


def _gen_change_geometry_prop(box_name, prop_name, value=None, z_val=None):
    """Generate ChangeProperty call for geometry modification."""
    if prop_name == 'Position':
        return (
            'oEditor.ChangeProperty(\n'
            '    [\n'
            '        "NAME:AllTabs",\n'
            '        [\n'
            '            "NAME:Geometry3DCmdTab",\n'
            '            [\n'
            '                "NAME:PropServers",\n'
            '                "{}:CreateBox:1"\n'
            '            ],\n'
            '            [\n'
            '                "NAME:ChangedProps",\n'
            '                [\n'
            '                    "NAME:Position",\n'
            '                    "X:="			, "-DielX/2",\n'
            '                    "Y:="			, "-DielY/2",\n'
            '                    "Z:="			, "{}"\n'
            '                ]\n'
            '            ]\n'
            '        ]\n'
            '    ])\n'.format(box_name, z_val)
        )
    elif prop_name == 'ZSize':
        return (
            'oEditor.ChangeProperty(\n'
            '    [\n'
            '        "NAME:AllTabs",\n'
            '        [\n'
            '            "NAME:Geometry3DCmdTab",\n'
            '            [\n'
            '                "NAME:PropServers",\n'
            '                "{}:CreateBox:1"\n'
            '            ],\n'
            '            [\n'
            '                "NAME:ChangedProps",\n'
            '                [\n'
            '                    "NAME:ZSize",\n'
            '                    "Value:="		, "{}"\n'
            '                ]\n'
            '            ]\n'
            '        ]\n'
            '    ])\n'.format(box_name, value)
        )
    return ''


def _gen_stackup_separator_and_reorg(current_d_id, dielectric_layers, layer_info):
    """
    Generate StackUp separator and organize variables for the first dielectric.
    This creates a clean variable organization in the HFSS UI.
    """
    lines = []
    lines.append('oDesign.ChangeProperty(')
    lines.append('    [')
    lines.append('        "NAME:AllTabs",')
    lines.append('        [')
    lines.append('            "NAME:LocalVariableTab",')
    lines.append('            [')
    lines.append('                "NAME:PropServers",')
    lines.append('                "LocalVariables"')
    lines.append('            ],')
    lines.append('            [')
    lines.append('                "NAME:NewProps",')
    lines.append('                [')
    lines.append('                    "NAME:StackUp",')
    lines.append('                    "PropType:="		, "SeparatorProp",')
    lines.append('                    "UserDef:="		, True,')
    lines.append('                    "Value:="		, ""')
    lines.append('                ]')

    # We will add all variables after the separator is created
    lines.append('            ],')
    lines.append('            [')
    lines.append('                "NAME:ChangedProps",')
    lines.append('                [')
    lines.append('                    "NAME:StackUp",')
    lines.append('                    "NewRowPosition:="	, 0')
    lines.append('                ],')

    # Re-express _high as formula
    lines.append('                [')
    lines.append('                    "NAME:' + current_d_id + '_high",')
    lines.append('                    "Value:="		, "' + current_d_id + '_low+' + current_d_id + '_h"')
    lines.append('                ],')

    # Add _h variable reposition
    lines.append('                [')
    lines.append('                    "NAME:' + current_d_id + '_h",')
    lines.append('                    "NewRowPosition:="	, 5')
    lines.append('                ]')

    lines.append('            ]')
    lines.append('        ]')
    lines.append('    ]')
    lines.append('])')

    return '\n'.join(lines)
